Repository knative-extensions/kn-plugin-admin, pull requests merged in 2020-12, with the labels that each got.

#25 update module dependency to latest version
  go.mod
  go.sum
  pkg/command/autoscaling/update.go
  pkg/command/autoscaling/update_test.go
  pkg/command/domain/list.go
  pkg/command/domain/set.go
  pkg/command/domain/set_test.go
  pkg/command/domain/unset.go
  pkg/command/domain/unset_test.go
  pkg/command/profiling/profiling.go
  pkg/command/profiling/profiling_test.go
  pkg/command/registry/add.go
  pkg/command/registry/add_test.go
  pkg/command/registry/list.go
  pkg/command/registry/remove.go
  pkg/command/registry/remove_test.go
  pkg/command/utils/utils.go
  pkg/command/utils/utils_test.go
  pkg/types.go
Labels: approved, cla: yes, lgtm, size/XXL

#31 Update github workflow go test to setup go 1.14
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#29 add autoscaling list command
  README.adoc
  pkg/command/autoscaling/autoscaling.go
  pkg/command/autoscaling/list.go
  pkg/command/autoscaling/list_test.go
  pkg/command/autoscaling/update.go
  test/e2e/kn_admin_test.go
Labels: approved, cla: yes, lgtm, size/L

#39 Add CODE_OF_CONDUCT.md and OWNER_ALIASES
  CODE_OF_CONDUCT.md
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#40 Avoid to print runtime error if kubectl context is not set
  core/root.go
  pkg/command/autoscaling/list.go
  pkg/command/autoscaling/list_test.go
  pkg/command/autoscaling/update.go
  pkg/command/autoscaling/update_test.go
  pkg/command/domain/list.go
  pkg/command/domain/list_test.go
  pkg/command/domain/set.go
  pkg/command/domain/set_test.go
  pkg/command/domain/unset.go
  pkg/command/domain/unset_test.go
  pkg/command/profiling/profiling.go
  pkg/command/profiling/profiling_test.go
  pkg/command/registry/add.go
  pkg/command/registry/add_test.go
  pkg/command/registry/list.go
  pkg/command/registry/list_test.go
  pkg/command/registry/registry_test.go
  pkg/command/registry/remove.go
  pkg/command/registry/remove_test.go
  pkg/testutil/command.go
  pkg/types.go
  pkg/types_test.go
  test/e2e/kn_admin_test.go
Labels: approved, cla: yes, lgtm, size/XL
