Repository knative-extensions/kn-plugin-admin, pull requests merged in 2021-02, with the labels that each got.

#38 Add support for plugin inline feature
  hack/build.sh
  plugin/plugin.go
  vendor/knative.dev/client/pkg/kn/plugin/manager.go
  vendor/knative.dev/client/pkg/kn/plugin/stat.go
  vendor/knative.dev/client/pkg/kn/plugin/stat_windows.go
  vendor/knative.dev/client/pkg/kn/plugin/verify.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#43 add CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#45 chore: Add missing release.sh
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/M
