Repository knative-extensions/kn-plugin-admin, pull requests merged in 2021-11, with the labels that each got.

#135 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/flags/podspec.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#136 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/errors/errors.go
  vendor/knative.dev/client/pkg/errors/factory.go
  vendor/knative.dev/client/pkg/kn/config/config.go
  vendor/knative.dev/client/pkg/kn/flags/podspec.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#138 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/config/config.go
  vendor/knative.dev/client/pkg/kn/config/types.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#137 Document maturity levels in sandbox
  README.adoc
Labels: cla: yes, approved, lgtm, size/XS

#140 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#141 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, lgtm, size/XS

#142 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/S

#143 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#144 [main] Update actions
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/XS

#145 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#146 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/autoscalerconfig.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: cla: yes, size/XL, approved, lgtm

#147 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/XS
