Repository knative-extensions/kn-plugin-admin, pull requests merged in 2021-08, with the labels that each got.

#98 Update go version to 1.16
  go.mod
Labels: approved, cla: yes, lgtm, size/XS

#99 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, approved, lgtm, size/XS

#101 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XS

#102 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#103 [main] Format Go code
  hack/tools.go
  test/e2e/kn_admin_test.go
Labels: cla: yes, approved, lgtm, size/XS

#104 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/commands/flags/sink.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#105 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, lgtm, size/XS

#106 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/XS
