Repository knative-extensions/kn-plugin-admin, pull requests merged in 2021-09, with the labels that each got.

#109 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#114 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/S

#112 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/eventing/v1/client.go
  vendor/knative.dev/client/pkg/eventing/v1/client_mock.go
  vendor/knative.dev/client/pkg/messaging/v1/subscriptions_client.go
  vendor/knative.dev/client/pkg/messaging/v1/subscriptions_client_mock.go
  vendor/knative.dev/client/pkg/serving/v1/client.go
  vendor/knative.dev/client/pkg/serving/v1alpha1/client.go
  vendor/knative.dev/client/pkg/serving/v1alpha1/client_mock.go
  vendor/knative.dev/client/pkg/sources/v1/container_client.go
  vendor/knative.dev/client/pkg/sources/v1/container_client_mock.go
  vendor/knative.dev/client/pkg/sources/v1beta2/ping_client.go
  vendor/knative.dev/client/pkg/sources/v1beta2/ping_client_mock.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: cla: yes, size/XL, approved, lgtm

#113 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/M

#117 Remove go-openapi replace from go.mod
  go.mod
  go.sum
  vendor/github.com/go-openapi/spec/.golangci.yml
  vendor/github.com/go-openapi/spec/.travis.yml
  vendor/github.com/go-openapi/spec/README.md
  vendor/github.com/go-openapi/spec/appveyor.yml
  vendor/github.com/go-openapi/spec/bindata.go
  vendor/github.com/go-openapi/spec/cache.go
  vendor/github.com/go-openapi/spec/contact_info.go
  vendor/github.com/go-openapi/spec/errors.go
  vendor/github.com/go-openapi/spec/expander.go
  vendor/github.com/go-openapi/spec/go.mod
  vendor/github.com/go-openapi/spec/go.sum
  vendor/github.com/go-openapi/spec/header.go
  vendor/github.com/go-openapi/spec/items.go
  vendor/github.com/go-openapi/spec/license.go
  vendor/github.com/go-openapi/spec/normalizer.go
  vendor/github.com/go-openapi/spec/operation.go
  vendor/github.com/go-openapi/spec/parameter.go
  vendor/github.com/go-openapi/spec/properties.go
  vendor/github.com/go-openapi/spec/ref.go
  vendor/github.com/go-openapi/spec/resolver.go
  vendor/github.com/go-openapi/spec/response.go
  vendor/github.com/go-openapi/spec/schema.go
  vendor/github.com/go-openapi/spec/schema_loader.go
  vendor/github.com/go-openapi/spec/security_scheme.go
  vendor/github.com/go-openapi/spec/spec.go
  vendor/github.com/go-openapi/spec/validations.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, approved, lgtm

#115 Add support for Darwin/arm64
  hack/release.sh
Labels: cla: yes, approved, lgtm, size/XS

#116 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/S

#118 Fix release script for darwin/arm64 bits
  hack/release.sh
Labels: cla: yes, approved, lgtm, size/XS

#120 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, lgtm, size/S

#121 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/flags/podspec.go
  vendor/knative.dev/client/pkg/kn/flags/podspec_helper.go
  vendor/knative.dev/client/pkg/util/parsing_helper.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#122 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/S

#123 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S
