Repository knative-extensions/kn-plugin-admin, pull requests merged in 2022-07, with the labels that each got.

#229 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#230 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#231 Remove broken license hack
  hack/build.sh
Labels: approved, lgtm, size/S

#228 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/XS, skip-review

#233 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#232 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/changeset/doc.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
