Repository knative-extensions/kn-plugin-admin, pull requests merged in 2022-10, with the labels that each got.

#254 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#255 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#256 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#258 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#259 Skip failing E2E test
  hack/build.sh
  test/e2e/kn_admin_test.go
Labels: approved, lgtm, size/XS
