Repository knative-extensions/kn-plugin-admin, pull requests merged in 2023-04, with the labels that each got.

#278 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, skip-review

#279 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#280 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#281 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/S, skip-review

#282 Skip e2e test in all release jobs
  test/e2e/kn_admin_test.go
Labels: approved, lgtm, size/XS

#283 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#284 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#285 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
